<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="scottplot.winforms" Version="4.1.69" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Tyuiu.BukhryakovAY.Sprint6.Task5.V11.Lib\Tyuiu.BukhryakovAY.Sprint6.Task5.V11.Lib.csproj" />
  </ItemGroup>

</Project>