<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="NewFolder\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Tyuiu.BukhryakovAY.Sprint6.Task3.V14.Lib\Tyuiu.BukhryakovAY.Sprint6.Task3.V14.Lib.csproj" />
  </ItemGroup>

</Project>